sudo: required
dist: xenial
language: python
python:
- '3.5'
- '2.7'
matrix:
  include:
  - env: HAVE_QD=no
  - env: HAVE_LONG_DOUBLE=no
  - env: HAVE_NUMPY=no
  - env:
    - HAVE_QD=no
    - HAVE_LONG_DOUBLE=no
cache:
- pip
addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libqd-dev
    - build-essential
    - libtool
    - autoconf
    - python-pip
    - python-dev
    - python-flake8
install:
- "./install-dependencies.sh $VIRTUAL_ENV"
- pip install -r requirements.txt
- python setup.py build
- python setup.py -q install
before_script:
- flake8 --max-line-length=120 --max-complexity=16 --ignore=E22,E241,E741 src
script:
- LD_LIBRARY_PATH="$VIRTUAL_ENV/lib" PY_IGNORE_IMPORTMISMATCH=1 py.test
- LD_LIBRARY_PATH="$VIRTUAL_ENV/lib" python setup.py sdist
notifications:
  on_success: change
  on_failure: always
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: fH9OGWX+9KLCiJhHN6Vxe8wlELuN/qhf37B1pX4Tm4C2SMx1DNfe2ZSulHF/LGgghFE+lYd5GMFC2cjKpjolP6wUrP0ESx0EjWQlczIDFIt4BdC8gkEfDdrV8ecm2mBKzOMMTKs8XMVPxLCMrxmILb0wyjKrBvA+nJTNO2Rd4aYpnwHWZLvklDoXvHP2Tgn69MV3Q38FqaGQvJaVKUIPbriHJlkG6DOAVPUFAia3DAY9Knrz2kqI4D4NaZQRU9TPmCcw7yz6jtiUVNIPLJiwiY7E9j2qnVpgyfQ7/L2JDxA6EjAbavoQ8xMmLGn3cvrtBz3iH9ZzQFO5Z/58iKVX6+Bro9+SaLj5EysBF9P13rqHiH714tI+f5zjKaohFpnENeCbKCxFcfSi6sn2xDpvHWOuPBdbJv7dciuFiFbsW1h/bP23t3kv2W2Of4ObZNh6+r43Q+qyEX8ZwO06itm11DrBXjvC5RoMpvh4J44rXX48/kqAr0DAkdogpsYmRWB0COkEAbDFrKFKYQXm9Ih+YlT1sjxgxbQaP5Xf6bnQhK3cm6fUAQF0W5wj2DvI97f1lr7DV8lvK1fDRHnmMB+LPvH5HnhFS9MHQy2PrMClrb0ukmVvavV2pSJ70BRxhhSkIHLKJqc03BmRDR21z530ZhLfIVhtdHZ7rhst7aaAgVo=
  file: dist/fpylll-*.tar.gz
  on:
    repo: fplll/fpylll
    tags: true
    all_branches: true

